#!/usr/bin/env bash
## .bash_profile
## #############
export dotfiles=$HOME/.dotfiles
export DOTFILES=$dotfiles


#if [[ -n $BASH ]] ; then
  # If BASH
  #source $DOTFILES/Bash/_bash_styles.sh
  #source $DOTFILES/_bash_aliases.sh
  #source $DOTFILES/_bash_functions.sh
  #my_aliases=($DOTFILES/**/aliases.sh)
  #my_functions=($DOTFILES/**/functions.sh)

  #for f in ${my_aliases[@]};   do source $f; done
  #for f in ${my_functions[@]}; do source $f; done

#elif [[ -n $ZSH_NAME ]] ; then
  # If ZSH
  # https://weimergeeks.com/wp/linux-bash/changing-the-prompt-in-zsh/
  #source $DOTFILES/ZSH/_zsh_styles.sh
  #typeset -U my_aliases
  #typeset -U my_functions
  #my_aliases=($DOTFILES/**/aliases.sh)
  #my_functions=($DOTFILES/**/functions.sh)
  #my_files=($my_aliases $my_functions)

  #for file in ${my_files}; do
  #  source $file
  #done
#fi

echo ""
echo ""
echo ""
bash ~/.dotfiles/Bash/raspberry
let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
let secs=$((${upSeconds}%60))
let mins=$((${upSeconds}/60%60))
let hours=$((${upSeconds}/3600%24))
let days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`

# get the load averages
read one five fifteen rest < /proc/loadavg

echo "$(tput setaf 2)
`date +"%A, %e %B %Y, %r"`
`uname -srmo`

$(tput sgr0)- Uptime.............: ${UPTIME}
$(tput sgr0)- Memory.............: `free | grep Mem | awk '{print $3/1024}'` MB (Used) / `cat /proc/meminfo | grep MemTotal | awk {'print $2/1024'}` MB (Total)
$(tput sgr0)- Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
$(tput sgr0)- Running Processes..: `ps ax | wc -l | tr -d " "`
$(tput sgr0)- IP Addresses.......: `hostname -I | /usr/bin/cut -d " " -f 1` and `wget -q -O - http://icanhazip.com/ | tail`

$(tput sgr0)"

source $DOTFILES/Bash/_bash_styles.sh
